language: php

php:
  - 5.6
  - 7.0
  - 7.1
  
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION='~2.8'
    - php: 5.6
      env: SYMFONY_VERSION='~3.0'

before_install:
  - composer self-update
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi;'
  
install: composer install

script: ./vendor/bin/phpunit